language: generic

matrix:
  include:
    - env: CC=gcc-4.9 CXX=g++-4.9
      os: linux
      sudo: false
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - g++-4.9
            - python-configparser

    - env: CC=gcc-6 CXX=g++-6
      os: osx
      sudo: false
      before_install:
        - brew update
        - brew cask uninstall --force oclint # See https://github.com/travis-ci/travis-ci/issues/8826 for details.
        - brew install gcc@6

    - env: CC="clang-3.8" CXX="clang++-3.8"
      os: linux
      sudo: false
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - clang-3.8
            - libiomp-dev
            - python-configparser

    - env: CC=clang-3.7 CXX=clang++-3.7
      os: osx
      sudo: false
      before_install:
        - brew update
        - brew install llvm37
        - brew install libomp
        - pip2 install configparser
      install:
        - export C_INCLUDE_PATH=$(llvm-config-3.7 --includedir)
        - export CPLUS_INCLUDE_PATH=$(llvm-config-3.7 --includedir)
        - export LIBRARY_PATH=$(llvm-config-3.7 --libdir)

script:
 - echo $GTEST_LIB
 - echo $GTEST_INCLUDE
 - echo $OPENMP_LIB
 - echo $OPENMP_INCLUDE
 - $CXX --version
 - mkdir build_test && cd "$_"
 - cmake -DNETWORKIT_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug ..
 - make -j2
 - export OMP_NUM_THREADS=2
 - ctest -V

notifications:
  email: false
